// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderManagement.DbContexts;

#nullable disable

namespace OrderManagement.Migrations
{
    [DbContext(typeof(OrderManagementContext))]
    [Migration("20260331120343_ApiKeyImplementation")]
    partial class ApiKeyImplementation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrderManagement.Entity.ApiKey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.HasIndex("OrderProductId");

                    b.ToTable("ApiKeys", (string)null);
                });

            modelBuilder.Entity("OrderManagement.Entity.ApiKeyPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApiKeyId")
                        .HasColumnType("bigint");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId");

                    b.ToTable("ApiKeyPermissions", (string)null);
                });

            modelBuilder.Entity("OrderManagement.Entity.Basket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("OrderManagement.Entity.BasketProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BasketId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.HasIndex("ProductId");

                    b.ToTable("BasketProducts");
                });

            modelBuilder.Entity("OrderManagement.Entity.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BasketId")
                        .HasColumnType("bigint");

                    b.Property<long>("InvoiceAddressId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OrderNo")
                        .HasColumnType("text");

                    b.Property<int?>("OrderStatus")
                        .HasColumnType("integer");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrderManagement.Entity.OrderProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("FileId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ProccessDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductValue")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("OrderManagement.Entity.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AcquisitionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("AreaKm2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int?>("CloudRate")
                        .HasColumnType("integer");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("District")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("DownloadLink")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool?>("IsClassified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsOrthorectified")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsPansharpened")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PreviewUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PriceStr")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Provider")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal?>("Resolution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 2,
                            Currency = "TRY",
                            IsDeleted = false,
                            Name = "API Key",
                            Price = 1000m,
                            PriceStr = "₺1000"
                        },
                        new
                        {
                            Id = 2L,
                            AcquisitionDate = new DateTime(2026, 3, 12, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            AreaKm2 = 42.8m,
                            CategoryId = 1,
                            City = "İstanbul",
                            CloudRate = 4,
                            Currency = "TRY",
                            Description = "Yüksek çözünürlüklü şehir uydu görüntüsü.",
                            District = "Beşiktaş",
                            DownloadLink = "https://example.com/downloads/product-1.zip",
                            IsClassified = true,
                            IsDeleted = false,
                            IsOrthorectified = true,
                            IsPansharpened = true,
                            Name = "İstanbul Avrupa Yakası Uydu Görüntüsü - Beşiktaş",
                            PreviewUrl = "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=1200",
                            Price = 18500m,
                            PriceStr = "₺18.500",
                            Provider = "Maxar",
                            Resolution = 0.3m,
                            ThumbnailUrl = "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=600"
                        },
                        new
                        {
                            Id = 3L,
                            AcquisitionDate = new DateTime(2026, 2, 28, 9, 40, 0, 0, DateTimeKind.Unspecified),
                            AreaKm2 = 87.4m,
                            CategoryId = 2,
                            City = "Ankara",
                            CloudRate = 9,
                            Currency = "TRY",
                            Description = "Tarım alanları için analiz verisi.",
                            District = "Gölbaşı",
                            DownloadLink = "https://example.com/downloads/product-2.zip",
                            IsClassified = true,
                            IsDeleted = false,
                            IsOrthorectified = true,
                            IsPansharpened = false,
                            Name = "Ankara Tarım Analizi - Gölbaşı",
                            PreviewUrl = "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=1200",
                            Price = 12400m,
                            PriceStr = "₺12.400",
                            Provider = "Planet",
                            Resolution = 0.5m,
                            ThumbnailUrl = "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=600"
                        },
                        new
                        {
                            Id = 4L,
                            AcquisitionDate = new DateTime(2026, 3, 5, 14, 20, 0, 0, DateTimeKind.Unspecified),
                            AreaKm2 = 58.9m,
                            CategoryId = 3,
                            City = "İzmir",
                            CloudRate = 6,
                            Currency = "TRY",
                            Description = "Kıyı ve şehir birleşik uydu görüntüsü.",
                            District = "Karşıyaka",
                            DownloadLink = "https://example.com/downloads/product-3.zip",
                            IsClassified = false,
                            IsDeleted = false,
                            IsOrthorectified = true,
                            IsPansharpened = true,
                            Name = "İzmir Kıyı Uydu Görüntüsü",
                            PreviewUrl = "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200",
                            Price = 21800m,
                            PriceStr = "₺21.800",
                            Provider = "Airbus",
                            Resolution = 0.4m,
                            ThumbnailUrl = "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=600"
                        },
                        new
                        {
                            Id = 5L,
                            AcquisitionDate = new DateTime(2026, 1, 19, 11, 10, 0, 0, DateTimeKind.Unspecified),
                            AreaKm2 = 65.1m,
                            CategoryId = 4,
                            City = "Bursa",
                            CloudRate = 3,
                            Currency = "TRY",
                            Description = "Sanayi alanı analiz görüntüsü.",
                            District = "Nilüfer",
                            DownloadLink = "https://example.com/downloads/product-4.zip",
                            IsClassified = true,
                            IsDeleted = false,
                            IsOrthorectified = true,
                            IsPansharpened = true,
                            Name = "Bursa Sanayi Bölgesi Uydu Verisi",
                            PreviewUrl = "https://images.unsplash.com/photo-1470115636492-6d2b56f9146d?w=1200",
                            Price = 16750m,
                            PriceStr = "₺16.750",
                            Provider = "Maxar",
                            Resolution = 0.3m,
                            ThumbnailUrl = "https://images.unsplash.com/photo-1470115636492-6d2b56f9146d?w=600"
                        },
                        new
                        {
                            Id = 6L,
                            AcquisitionDate = new DateTime(2026, 3, 18, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            AreaKm2 = 73.6m,
                            CategoryId = 5,
                            City = "Antalya",
                            CloudRate = 7,
                            Currency = "TRY",
                            Description = "Turizm ve kıyı analiz verisi.",
                            District = "Alanya",
                            DownloadLink = "https://example.com/downloads/product-5.zip",
                            IsClassified = true,
                            IsDeleted = false,
                            IsOrthorectified = true,
                            IsPansharpened = false,
                            Name = "Antalya Kıyı Uydu Paketi",
                            PreviewUrl = "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1200",
                            Price = 14300m,
                            PriceStr = "₺14.300",
                            Provider = "Planet",
                            Resolution = 0.5m,
                            ThumbnailUrl = "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=600"
                        },
                        new
                        {
                            Id = 7L,
                            AcquisitionDate = new DateTime(2026, 2, 11, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            AreaKm2 = 120.3m,
                            CategoryId = 2,
                            City = "Konya",
                            CloudRate = 12,
                            Currency = "TRY",
                            Description = "Geniş tarım alanı gözlemi.",
                            District = "Selçuklu",
                            DownloadLink = "https://example.com/downloads/product-6.zip",
                            IsClassified = true,
                            IsDeleted = false,
                            IsOrthorectified = true,
                            IsPansharpened = false,
                            Name = "Konya Tarım Uydu Görüntüsü",
                            PreviewUrl = "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200",
                            Price = 9800m,
                            PriceStr = "₺9.800",
                            Provider = "Sentinel",
                            Resolution = 1.0m,
                            ThumbnailUrl = "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600"
                        });
                });

            modelBuilder.Entity("OrderManagement.Entity.ProductClass", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("Id"));

                    b.Property<string>("ClassName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("PixelCount")
                        .HasColumnType("integer");

                    b.Property<long?>("ProductId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductClasses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ClassName = "Yerleşim",
                            ColorHex = "#ff6b6b",
                            PixelCount = 124500,
                            ProductId = 2L
                        },
                        new
                        {
                            Id = 2L,
                            ClassName = "Yol",
                            ColorHex = "#ffd166",
                            PixelCount = 48210,
                            ProductId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            ClassName = "Yeşil Alan",
                            ColorHex = "#06d6a0",
                            PixelCount = 38120,
                            ProductId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            ClassName = "Su",
                            ColorHex = "#118ab2",
                            PixelCount = 19340,
                            ProductId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            ClassName = "Tarım Alanı",
                            ColorHex = "#8ac926",
                            PixelCount = 211430,
                            ProductId = 3L
                        },
                        new
                        {
                            Id = 6L,
                            ClassName = "Boş Arazi",
                            ColorHex = "#c2b280",
                            PixelCount = 73450,
                            ProductId = 3L
                        },
                        new
                        {
                            Id = 7L,
                            ClassName = "Yol",
                            ColorHex = "#adb5bd",
                            PixelCount = 19410,
                            ProductId = 3L
                        },
                        new
                        {
                            Id = 8L,
                            ClassName = "Su",
                            ColorHex = "#1982c4",
                            PixelCount = 16420,
                            ProductId = 3L
                        },
                        new
                        {
                            Id = 9L,
                            ClassName = "Yerleşim",
                            ColorHex = "#ef476f",
                            PixelCount = 98400,
                            ProductId = 4L
                        },
                        new
                        {
                            Id = 10L,
                            ClassName = "Su",
                            ColorHex = "#3a86ff",
                            PixelCount = 62450,
                            ProductId = 4L
                        },
                        new
                        {
                            Id = 11L,
                            ClassName = "Liman",
                            ColorHex = "#8338ec",
                            PixelCount = 14200,
                            ProductId = 4L
                        },
                        new
                        {
                            Id = 12L,
                            ClassName = "Sanayi",
                            ColorHex = "#ff9f1c",
                            PixelCount = 110230,
                            ProductId = 5L
                        },
                        new
                        {
                            Id = 13L,
                            ClassName = "Yol",
                            ColorHex = "#adb5bd",
                            PixelCount = 36610,
                            ProductId = 5L
                        },
                        new
                        {
                            Id = 14L,
                            ClassName = "Yeşil Alan",
                            ColorHex = "#2ec4b6",
                            PixelCount = 22780,
                            ProductId = 5L
                        },
                        new
                        {
                            Id = 15L,
                            ClassName = "Otel Bölgesi",
                            ColorHex = "#ff595e",
                            PixelCount = 45220,
                            ProductId = 6L
                        },
                        new
                        {
                            Id = 16L,
                            ClassName = "Kıyı",
                            ColorHex = "#1982c4",
                            PixelCount = 33910,
                            ProductId = 6L
                        },
                        new
                        {
                            Id = 17L,
                            ClassName = "Yol",
                            ColorHex = "#6c757d",
                            PixelCount = 20110,
                            ProductId = 6L
                        },
                        new
                        {
                            Id = 18L,
                            ClassName = "Yeşil Alan",
                            ColorHex = "#8ac926",
                            PixelCount = 28440,
                            ProductId = 6L
                        },
                        new
                        {
                            Id = 19L,
                            ClassName = "Tarım Alanı",
                            ColorHex = "#8ac926",
                            PixelCount = 402800,
                            ProductId = 7L
                        },
                        new
                        {
                            Id = 20L,
                            ClassName = "Boş Arazi",
                            ColorHex = "#c2b280",
                            PixelCount = 95420,
                            ProductId = 7L
                        },
                        new
                        {
                            Id = 21L,
                            ClassName = "Sulama Kanalı",
                            ColorHex = "#3a86ff",
                            PixelCount = 11840,
                            ProductId = 7L
                        });
                });

            modelBuilder.Entity("OrderManagement.Entity.ApiKey", b =>
                {
                    b.HasOne("OrderManagement.Entity.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderManagement.Entity.OrderProduct", "OrderProduct")
                        .WithMany()
                        .HasForeignKey("OrderProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("OrderProduct");
                });

            modelBuilder.Entity("OrderManagement.Entity.ApiKeyPermission", b =>
                {
                    b.HasOne("OrderManagement.Entity.ApiKey", "ApiKey")
                        .WithMany("Permissions")
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiKey");
                });

            modelBuilder.Entity("OrderManagement.Entity.BasketProduct", b =>
                {
                    b.HasOne("OrderManagement.Entity.Basket", "Basket")
                        .WithMany()
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderManagement.Entity.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OrderManagement.Entity.Order", b =>
                {
                    b.HasOne("OrderManagement.Entity.Basket", "Basket")
                        .WithMany()
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");
                });

            modelBuilder.Entity("OrderManagement.Entity.OrderProduct", b =>
                {
                    b.HasOne("OrderManagement.Entity.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderManagement.Entity.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OrderManagement.Entity.ProductClass", b =>
                {
                    b.HasOne("OrderManagement.Entity.Product", "Product")
                        .WithMany("Classes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OrderManagement.Entity.ApiKey", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("OrderManagement.Entity.Product", b =>
                {
                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
