// <auto-generated />
using System;
using MapManagement.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MapManagement.Migrations
{
    [DbContext(typeof(MapManagementContext))]
    [Migration("20260401192234_LayerEdit")]
    partial class LayerEdit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MapManagement.Entity.Layer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Format")
                        .HasColumnType("text");

                    b.Property<bool>("IsBaseMap")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<long>("LayerGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("LayerName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Opacity")
                        .HasColumnType("double precision");

                    b.Property<int>("OrderNo")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LayerGroupId");

                    b.ToTable("Layers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 4, 1, 19, 22, 33, 570, DateTimeKind.Utc).AddTicks(4632),
                            IsBaseMap = true,
                            IsDeleted = false,
                            IsVisible = true,
                            LayerGroupId = 1L,
                            Name = "Carto Light",
                            Opacity = 1.0,
                            OrderNo = 0,
                            Type = 0,
                            Url = "https://{a-d}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 4, 1, 19, 22, 33, 570, DateTimeKind.Utc).AddTicks(4639),
                            IsBaseMap = true,
                            IsDeleted = false,
                            IsVisible = true,
                            LayerGroupId = 1L,
                            Name = "OSM Standart",
                            Opacity = 1.0,
                            OrderNo = 0,
                            Type = 0,
                            Url = "https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2026, 4, 1, 19, 22, 33, 570, DateTimeKind.Utc).AddTicks(4640),
                            IsBaseMap = true,
                            IsDeleted = false,
                            IsVisible = true,
                            LayerGroupId = 1L,
                            Name = "OSM Hot",
                            Opacity = 1.0,
                            OrderNo = 0,
                            Type = 0,
                            Url = "https://{a-c}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png"
                        });
                });

            modelBuilder.Entity("MapManagement.Entity.LayerGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LayerGroups");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            IsDeleted = false,
                            Name = "Altlık Haritalar"
                        });
                });

            modelBuilder.Entity("MapManagement.Entity.Layer", b =>
                {
                    b.HasOne("MapManagement.Entity.LayerGroup", "LayerGroup")
                        .WithMany("Layers")
                        .HasForeignKey("LayerGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LayerGroup");
                });

            modelBuilder.Entity("MapManagement.Entity.LayerGroup", b =>
                {
                    b.Navigation("Layers");
                });
#pragma warning restore 612, 618
        }
    }
}
