// <auto-generated />
using System;
using MapManagement.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MapManagement.Migrations
{
    [DbContext(typeof(MapManagementContext))]
    [Migration("20260622150127_AltlıkHaritalarGüncnelendi2")]
    partial class AltlıkHaritalarGüncnelendi2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MapManagement.Entity.Layer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Format")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("LayerName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Opacity")
                        .HasColumnType("double precision");

                    b.Property<int>("OrderNo")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Layers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 1, 26, 930, DateTimeKind.Utc).AddTicks(6182),
                            IsDeleted = false,
                            IsVisible = true,
                            Name = "OSM Standart",
                            Opacity = 1.0,
                            OrderNo = 1,
                            Type = 1,
                            Url = "https://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 1, 26, 930, DateTimeKind.Utc).AddTicks(6188),
                            IsDeleted = false,
                            IsVisible = false,
                            Name = "Yükseklik Haritası",
                            Opacity = 1.0,
                            OrderNo = 2,
                            Type = 1,
                            Url = "https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 1, 26, 930, DateTimeKind.Utc).AddTicks(6190),
                            IsDeleted = false,
                            IsVisible = false,
                            Name = "Topografik Harita",
                            Opacity = 1.0,
                            OrderNo = 3,
                            Type = 1,
                            Url = "https://{a-c}.tile.opentopomap.org/{z}/{x}/{y}.png"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2026, 6, 22, 15, 1, 26, 930, DateTimeKind.Utc).AddTicks(6191),
                            IsDeleted = false,
                            IsVisible = false,
                            Name = "Gece Haritası",
                            Opacity = 1.0,
                            OrderNo = 4,
                            Type = 1,
                            Url = "https://basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
